nelmio_cors:
    defaults:
        allow_credentials: true  # Permet l'envoi des cookies (important pour les sessions)
        allow_origin: ['http://localhost:5173']  # Permet uniquement l'origine de votre front-end
        allow_headers: ['*'] # ['Content-Type', 'Authorization']  # Autorise les en-têtes nécessaires
        allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
        max_age: 3600
        hosts: []
